title: Homebrew Documentation
description: Documentation for the missing package manager for macOS (or Linux).

remote_theme: Homebrew/brew.sh

exclude:
  - bin
  - CNAME
  - Gemfile*
  - vale-styles
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/homebrew-256x256.png
      search_name: Documentation
      search_site: docs
  - scope:
      path: governance
    values:
      category: governance-archives

kramdown:
  toc_levels: 2..3

logo: /assets/img/homebrew-256x256.png

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
