version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    # The actions in triage-issues.yml are updated in the Homebrew/.github repo
    ignore:
      - dependency-name: actions/stale
      - dependency-name: dessant/lock-threads

  - package-ecosystem: bundler
    directory: /Library/Homebrew
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    versioning-strategy: lockfile-only
